"""Add GIN index for task FTS

Revision ID: e788b7dbfd3a
Revises: 2b7a927f562c
Create Date: 2026-07-23 15:23:27.327704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e788b7dbfd3a'
down_revision: Union[str, Sequence[str], None] = '2b7a927f562c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', title) || to_tsvector('russian', coalesce(description, ''))", persisted=True), nullable=False))
    op.create_index('idx_task_fts', 'tasks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_fts', table_name='tasks', postgresql_using='gin')
    op.drop_column('tasks', 'search_vector')
    # ### end Alembic commands ###
