"""Add Unique Constraint Index to 'tags' table

Revision ID: ec3fe8c1c944
Revises: 3c24f81e959d
Create Date: 2026-07-06 21:57:06.189729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec3fe8c1c944'
down_revision: Union[str, Sequence[str], None] = '3c24f81e959d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_project_id'), table_name='tags')
    op.create_index('uq_idx_tag_name_project_id', 'tags', ['name', 'project_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_idx_tag_name_project_id', table_name='tags')
    op.create_index(op.f('ix_tags_project_id'), 'tags', ['project_id'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    # ### end Alembic commands ###
